travis:
  secure:
    BINSTAR_TOKEN: eN5xczSYHtk3OWEC/uz7zMxQzaLw3BQjRAymkAv2eDNoM8cvx7xVyLPRh4wmRjDT/0xgfRraJPxa7oFClczlSHAOGArX3IlIBzIchKO6hh5B6lNPiizqyHgoCDyTeOMa03uE5HSWZMu3GM13Rmgzt205PTZrhuVTK5AwhqzUApwaQWSK6qEtlDMhWazzk/6ri9ghHBkJGNhWHYvMQ1xogWWItrLdyyv1eGdwkq929qjBo6xyRuKK83nKpfsdDtzEU3zwAddv1JpCIEnAgEEeV7nffNRs63ykYBRprmAYSrAx2ye3hGbx5VxLoclcRFwQx6ollGN4apNjPBZdDVOnfm7Vl3SA8PpLC3+Aqfr4TnAf238ay8c2JzUQRRz7UpzRg47EPM6mfzQZZxpIuwlBnCw22ZXjLFFUYcal3ZLnN1CedUCydf7dXdkUnX1HvIUxJH6IiibjezcoQwGsV2Mp2SreMu91wdXOg7C0asyuMrqIFnCLLdWaAPqqGMPzZ79z9j/0PxuEeIpKRCnl0BRyr9pdu+2dj6e3J4swbMkCVlWmdMs1D5f1/hptN6IpHxNoeRxcTQUESv9TWcmiaDr/1XDRyGjgco2SnwTbS8Jt1Gd139l4MPWGbBNJdpM6mCd7+1bGLojp2kOmXk3crPlz3tUoo9H1BH5/x1Yrvipix2k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
