travis:
  secure:
    BINSTAR_TOKEN: 5gD5FCU63te0Jc2cb8F2vN+D8xi5zcJUWQ3R7qQ2qel/k7xjxV+20x+SShL2tq+SIAcTA1tQ1I0UQElteJdPA4CknvA0oxNu1/sF/cQCaW0REubcR6Z+HhJG0KgktfgcgaEYFKGInkm88nPbpKN/qb8yxkhWQYOAHpKx0eaqTyE/I4BaJ4zMaCcC3AwrHTIKbYfXEpzXJDyFFOjBqDHWZMQuGNVNjbtq/UT+fx3YE+W501yJtX0x2k5+OILwZf9IpsExJgDulcWPAB1vjsItljD/r7QbcDLjDr5NWdl/wHsuyE2fug+ZeWOk6HuHFtvV5bV+MO2fcfnx4GD5qBPLB0mtRab9jM1CmrS30TLrJxEYbIzuROidx8xGnw+J6cIFAYK3fK5nxZ6V/0eJdWLdj6KCVGG6Yz0ZAq6sMMIci/i+9VEPN7zpbxT1AStmfKkah0t/v6V3FIJLcSOic2E+q3HjOhSlls8DH+Teo0n9YXZw3LnYuGMYmb7LCigpcDI2sMhIbZuhNOC+ucqnD7L6QHMAC3mo8z1QIYZ3/51XM+3oH/qXTG5cKf2fqnFLeZrmRjGB6Vx8SRljkY+rLLdHvpjz2Z1KXVkbHeYMH9OgqRnldZC53dhL6N8p6h2DnfptF5Psl5IBY4mbYLufKBnCTjHmxXetM+PiRxj9xXok8q8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
